name: CI

on:
  pull_request:
    branches:
      - main   # main ブランチ向けのPRのみ対象
    types:
      - opened        # PR作成時
      - synchronize   # コミット追加・更新時
      - reopened      # 再オープン時


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v

      - name: 依存パッケージをインストール
        run: npm ci

      - name: テストを実行
        run: npm test
